### ISSUE TITLE
listview padding not as predicted, it's bigger that the passed EdgeInsets, And the passed padding is set to a fixed Container out of the listview,

### ISSUE THREAD

**Issue by AlaaEldeenYsr** [MSVCode/scroll_snap_list#2]

**Comment by AlaaEldeenYsr** [comment]
The passed Padding with the black line is not as expected it's bigger, and also the passed padding is set to the Container above the listview with the red line and this is not wanted i think
![Screenshot_20200322-030315](https://user-images.githubusercontent.com/52201392/77240295-f67c0c00-6bec-11ea-937e-dbf7a8b27cde.jpg)

**Comment by MSVCode** [comment]
hi @AlaaEldeenYsr, this is the intended behavior for ScrollSnapList, as the main purpose is to "snap" active child to the center of the Component, the black line padding in your image is the result of calculation in order to center the "Adel Karan amin" card.

If you're not using the "snap" feature, it might be better to use Flutter's ListView widget directly.

**Comment by Ibtesam-Mahmood** [comment]
hi @MSVCode, is it possible to somehow offset the center of the list to avoid this. I wish to avoid the top padding on a vertically oriented list.
